export const CATEGORIES = 'categories'
export const SERVERS = 'users/servers'
export const PRODUCTS = 'products'
export const ORDERS = 'orders'
export const SALES = 'sales'
export const BASE_URL = 'http://localhost:3000/'
